import type { Sprite } from "./PixelArt";

export const grassBlock: Sprite = {
  palette: { G: "#6aaa3a", g: "#4f8a2b", D: "#8b5a2b", d: "#6b4421", s: "#a7774a" },
  art: [
    "GGGGGGGGGGGGGGGG",
    "GGgGGGGGGgGGGGGG",
    "GGGGGgGGGGGGGgGG",
    "gGGGGGGGGGGGGGGg",
    "GgGDGGgGGDGGGgDG",
    "DGDDDgDDGDDDGDDD",
    "DDDsDDDDDDdDDDDD",
    "DDdDDDDsDDDDDDsD",
    "DDDDDdDDDDDDDDDD",
    "DsDDDDDDDdDDsDDD",
    "DDDDDDsDDDDDDDDD",
    "DdDDDDDDDDDsDDdD",
    "DDDDsDDDdDDDDDDD",
    "DDDDDDDDDDDDsDDD",
    "DsDDDdDDDDDDDDDD",
    "DDDDDDDDDsDDDDdD",
  ],
};

export const houseScene: Sprite = {
  palette: {
    R: "#a8412f", r: "#7f2f22", k: "#3a4048", C: "#9a4a36", c: "#7a3628",
    W: "#d6a46a", w: "#b9854c", F: "#5a3a1f", B: "#8fd3f0", b: "#d8f2fc",
    D: "#7a4b26", K: "#f0b43c", L: "#5c9e35", l: "#3d7323", T: "#6b4421", t: "#553519",
    // crane, concrete, plank block
    Y: "#f0b43c", y: "#c98f22", S: "#9aa1a8", s: "#767d85", P: "#c8935a", p: "#9c6b3a",
    // worker: skin, vest, reflective stripe, jeans, boots, hammer handle
    e: "#e0ac7e", O: "#f26b1d", v: "#f4f1a8", J: "#3b5998", n: "#2e2218", H: "#a0703d",
  },
  art: [
    ".....Y......................................",
    ".....Y......................................",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.",
    "y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
    "SSS.Y.yYYY...........................kk.....",
    "sss.Y.yYBB............................k.....",
    "....YyyYYY............YYY..SS.........k.....",
    "....Y.y..............YYYYY.SS.........k.....",
    "....Y.y...............eee...H.........k.....",
    "....Yyy...............eee..H..........k.....",
    "....Y.y..............OOOOOe...........k.....",
    "....Y.y..............OvvvO...........kkk....",
    "....Yyy..............OOOOO..........PPPPP...",
    "....Y.y...............JJ............ppppp...",
    "....Y.y...............JJ..kkkk......PPpPP...",
    "....Yyy...............nn...cC.......ppppp...",
    "....Y.y...............rr...Cc.......PPPPp...",
    "....Y.y..............rRRr..cC...............",
    "....Yyy.............rRRRRr.Cc...............",
    "....Y.y............rrrrrrrrcC...............",
    "....Y.y...........rRRRRRRRRrc...............",
    "....Yyy..........rRRRRRRRRRRr...............",
    "....Y.y.........rrrrrrrrrrrrrr.......LLL....",
    "....Y.y........rRRRRRRRRRRRRRRr.....LLlLL...",
    "....Yyy.......rRRRRRRRRRRRRRRRRr...LLLLLlL..",
    "....Y.y......rrrrrrrrrrrrrrrrrrrr..LlLLLLL..",
    "....Y.y......FwwwwwwwwwwwwwwwwwwF..LLLLlLL..",
    "....Yyy......FWWWWWWWWWWWWWWWWWWF...LLLLL...",
    "....Y.y......FWWFFFFFWWWWWWWWWWWF...LTtL....",
    "....Y.y......FwwFbFBFwwwwFFFFwwwF....Tt.....",
    "....Yyy......FWWFBFBFWWWWFDDFWWWF....Tt.....",
    "....Y.y......FWWFFFFFWWWWFDDFWWWF....Tt.....",
    "....Y.y......FwwwwwwwwwwwFDKFwwwF....Tt.....",
    "....Yyy......FWWWWWWWWWWWFDDFWWWF....Tt.....",
    "....Y.y......FWWWWWWWWWWWFDDFWWWF....Tt.....",
    "...SSSSS.....FwwwwwwwwwwwFDDFwwwF....Tt.....",
  ],
};

const stone = { S: "#8d949c", s: "#6a7179", H: "#a0703d", h: "#7a5229" };

export const icons = {
  house: {
    palette: { R: "#a8412f", W: "#d6a46a", B: "#8fd3f0", D: "#7a4b26" },
    art: [
      ".....RR.....",
      "....RRRR....",
      "...RRRRRR...",
      "..RRRRRRRR..",
      ".RRRRRRRRRR.",
      "RRRRRRRRRRRR",
      ".WWWWWWWWWW.",
      ".WBBWWWWDDW.",
      ".WBBWWWWDDW.",
      ".WWWWWWWDDW.",
      ".WWWWWWWDDW.",
      ".WWWWWWWDDW.",
    ],
  },
  hammer: {
    palette: stone,
    art: [
      ".SSSSSSSSS..",
      "SSSSSSSSSSs.",
      "SSSSSSSSSSs.",
      ".sssssssss..",
      "....Hh......",
      "....Hh......",
      "....Hh......",
      "....Hh......",
      "....Hh......",
      "....Hh......",
      "...HHhh.....",
      "...hhhh.....",
    ],
  },
  bricks: {
    palette: { B: "#b5533c", b: "#8e3e2c", M: "#d9cfc4" },
    art: [
      "BBBBBMBBBBBB",
      "bbbbbMbbbbbb",
      "MMMMMMMMMMMM",
      "BBMBBBBBMBBB",
      "bbMbbbbbMbbb",
      "MMMMMMMMMMMM",
      "BBBBBMBBBBBB",
      "bbbbbMbbbbbb",
      "MMMMMMMMMMMM",
      "BBMBBBBBMBBB",
      "bbMbbbbbMbbb",
    ],
  },
  snowflake: {
    palette: { I: "#4fa8d8" },
    art: [
      ".....I.....",
      ".I..III..I.",
      "..I..I..I..",
      "...I.I.I...",
      ".I..III..I.",
      "IIIIIIIIIII",
      ".I..III..I.",
      "...I.I.I...",
      "..I..I..I..",
      ".I..III..I.",
      ".....I.....",
    ],
  },
  wrench: {
    palette: stone,
    art: [
      "......SS..SS",
      "......SS..SS",
      "......SSSSSs",
      ".....SSSSSs.",
      "....SSs.....",
      "...SSs......",
      "..SSs.......",
      ".SSs........",
      "SSs.........",
      "Ss..........",
    ],
  },
  pickaxe: {
    palette: stone,
    art: [
      "..SSSSS.....",
      "...SSSSSS...",
      "......SSSS..",
      ".......SSSS.",
      "......HhSSS.",
      ".....Hh..SSS",
      "....Hh....SS",
      "...Hh.....SS",
      "..Hh......SS",
      ".Hh........S",
      "Hh..........",
      "h...........",
    ],
  },
  check: {
    palette: { G: "#3f7a26" },
    art: [
      ".......G",
      "......GG",
      ".....GG.",
      "G...GG..",
      "GG.GG...",
      ".GGG....",
      "..G.....",
    ],
  },
} satisfies Record<string, Sprite>;
